---
docker_kernel_min_version: '0'

# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
# https://download.docker.com/linux/centos/7/x86_64/stable/Packages/
# https://yum.dockerproject.org/repo/main/centos/7
# or do 'yum --showduplicates list docker-engine'
docker_versioned_pkg:
  'latest': docker-engine
  '1.12': docker-engine-1.12.6-1.0.3.el7
  '17.03': docker-engine-17.03.1.ce-3.0.1.el7
  '17.06': docker-engine-17.06.2.ol-1.0.1.el7
  'stable': docker-engine-17.03.1.ce-3.0.1.el7
  'edge': docker-engine-17.06.2.ol-1.0.1.el7

docker_selinux_versioned_pkg:
  'latest': docker-engine-selinux
  '1.12': docker-engine-selinux-1.12.6-1.0.3.el7
  '17.03': docker-engine-selinux-17.03.1.ce-3.0.1.el7
  '17.06': docker-engine-selinux-17.06.2.ol-1.0.1.el7
  'stable': docker-engine-selinux-17.03.1.ce-3.0.1.el7
  'edge': docker-engine-selinux-17.06.2.ol-1.0.1.el7


docker_package_info:
  pkg_mgr: yum
  pkgs:
    - name: "{{ docker_selinux_versioned_pkg[docker_selinux_version | string] }}"
      yum_conf: "{{ docker_yum_conf }}"
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      yum_conf: "{{ docker_yum_conf }}"

docker_repo_key_info:
  pkg_key: ''
  repo_keys: []

docker_repo_info:
  pkg_repo: ''
  repos: []
